import React, { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import AccountLayout from "@/components/layout/AccountLayout";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { User, MapPin, Calendar, Weight, DollarSign, ShieldCheck, ArrowRight, Loader2, Package, Search } from "lucide-react";
import { cn } from "@/lib/utils";
import { apiClient } from "@/lib/api-client";

interface Match {
  id: string;
  shipment_id: string;
  listing_id: string;
  match_score: number;
  status: "pending" | "interested" | "accepted" | "rejected";
  shipment?: {
    title: string;
    origin_city: string;
    destination_city: string;
    weight: string;
    offered_price: string;
  };
  listing?: {
    user?: {
      first_name: string;
      last_name: string;
    };
    origin_city: string;
    destination_city: string;
    departure_date: string;
    price_per_kg: string;
  };
}

export default function MyMatches() {
  const [activeTab, setActiveTab] = useState<"senders" | "travelers">("senders");

  const { data: matchesData, isLoading } = useQuery({
    queryKey: ["matches", activeTab],
    queryFn: async () => {
      const endpoint = activeTab === "senders" ? "/matches/for-my-shipments" : "/matches/interested-in-my-trips";
      const response = await apiClient.get(endpoint);
      return response.data.data as Match[];
    }
  });

  const expressInterestMutation = useMutation({
    mutationFn: (matchId: string) => apiClient.post(`/matches/${matchId}/express-interest`),
    onSuccess: () => {
      toast.success("Interest expressed! Traveler has been notified.");
    }
  });

  const acceptMatchMutation = useMutation({
    mutationFn: (matchId: string) => apiClient.post(`/matches/${matchId}/accept`, { agreed_price: 50, currency: "USD" }),
    onSuccess: (data) => {
      toast.success("Match accepted! Booking created.");
      // In a real app, redirect to booking detail
    }
  });

  return (
    <AccountLayout>
      <div className="space-y-8">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <h2 className="text-2xl font-bold text-carry-darker">Smart Matches</h2>
            <p className="text-gray-500">Pairs generated by our matching engine based on route, date and capacity.</p>
          </div>
          
          <div className="flex bg-gray-100 p-1 rounded-sm self-start">
            <button 
              onClick={() => setActiveTab("senders")}
              className={cn(
                "px-4 py-2 text-xs font-bold uppercase tracking-widest transition-all rounded-sm",
                activeTab === "senders" ? "bg-white text-carry-light shadow-sm" : "text-gray-400 hover:text-gray-600"
              )}
            >
              For My Shipments
            </button>
            <button 
              onClick={() => setActiveTab("travelers")}
              className={cn(
                "px-4 py-2 text-xs font-bold uppercase tracking-widest transition-all rounded-sm",
                activeTab === "travelers" ? "bg-white text-carry-light shadow-sm" : "text-gray-400 hover:text-gray-600"
              )}
            >
              Interested in My Trips
            </button>
          </div>
        </div>

        {isLoading ? (
          <div className="p-20 flex justify-center">
            <Loader2 className="w-10 h-10 animate-spin text-carry-light" />
          </div>
        ) : matchesData && matchesData.length > 0 ? (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {matchesData.map((match) => (
              <Card key={match.id} className="border-none shadow-sm overflow-hidden group hover:shadow-md transition-all bg-white">
                <CardContent className="p-6 space-y-6">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <div className="bg-carry-light/10 text-carry-light px-2 py-1 rounded-sm text-[10px] font-bold uppercase tracking-widest">
                        {match.match_score}% Match
                      </div>
                      <Badge variant="outline" className="text-[10px] uppercase font-bold tracking-widest border-gray-100 text-gray-400">
                        {match.status}
                      </Badge>
                    </div>
                    <button className="text-gray-300 hover:text-carry-darker transition-colors">
                      <Search className="w-4 h-4" />
                    </button>
                  </div>

                  {activeTab === "senders" ? (
                    <div className="space-y-6">
                      <div className="flex items-center gap-4">
                        <div className="w-12 h-12 rounded-full bg-gray-100 flex items-center justify-center text-carry-muted border-2 border-white shadow-sm overflow-hidden">
                          <User className="w-6 h-6" />
                        </div>
                        <div className="flex flex-col">
                          <span className="font-bold text-carry-darker text-[15px]">
                            {match.listing?.user?.first_name} {match.listing?.user?.last_name}
                          </span>
                          <div className="flex items-center gap-1">
                            <ShieldCheck className="w-3 h-3 text-carry-light" />
                            <span className="text-[10px] font-bold text-carry-light uppercase tracking-tight">Verified Traveler</span>
                          </div>
                        </div>
                      </div>

                      <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-1">
                          <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Route</p>
                          <p className="text-xs font-bold text-carry-darker flex items-center gap-1">
                            {match.listing?.origin_city} <ArrowRight className="w-3 h-3" /> {match.listing?.destination_city}
                          </p>
                        </div>
                        <div className="space-y-1">
                          <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Departure</p>
                          <p className="text-xs font-bold text-carry-darker flex items-center gap-1">
                            <Calendar className="w-3 h-3" /> {match.listing?.departure_date ? new Date(match.listing.departure_date).toLocaleDateString() : "TBD"}
                          </p>
                        </div>
                      </div>

                      <Button 
                        onClick={() => expressInterestMutation.mutate(match.id)}
                        disabled={match.status !== "pending"}
                        className="w-full bg-carry-light hover:bg-carry-light/90 text-white font-bold h-10 text-xs uppercase tracking-widest"
                      >
                        {match.status === "pending" ? "Express Interest" : match.status === "interested" ? "Waiting for response" : "Match Accepted"}
                      </Button>
                    </div>
                  ) : (
                    <div className="space-y-6">
                      <div className="flex items-center gap-4">
                        <div className="w-12 h-12 rounded-sm bg-carry-bg flex items-center justify-center text-carry-light">
                          <Package className="w-6 h-6" />
                        </div>
                        <div className="flex flex-col">
                          <span className="font-bold text-carry-darker text-[15px]">{match.shipment?.title}</span>
                          <span className="text-xs text-gray-400">{match.shipment?.weight}kg · Offered {match.shipment?.offered_price}</span>
                        </div>
                      </div>

                      <div className="grid grid-cols-2 gap-4">
                        <div className="space-y-1">
                          <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Route</p>
                          <p className="text-xs font-bold text-carry-darker flex items-center gap-1">
                            {match.shipment?.origin_city} <ArrowRight className="w-3 h-3" /> {match.shipment?.destination_city}
                          </p>
                        </div>
                        <div className="space-y-1">
                          <p className="text-[10px] font-bold uppercase tracking-widest text-gray-400">Sender Offer</p>
                          <p className="text-xs font-bold text-carry-darker flex items-center gap-1">
                            <DollarSign className="w-3 h-3" /> {match.shipment?.offered_price} (Escrow Protected)
                          </p>
                        </div>
                      </div>

                      <div className="flex gap-3">
                        <Button variant="outline" className="flex-1 font-bold h-10 text-xs uppercase tracking-widest">
                          Reject
                        </Button>
                        <Button 
                          onClick={() => acceptMatchMutation.mutate(match.id)}
                          className="flex-[2] bg-carry-light hover:bg-carry-light/90 text-white font-bold h-10 text-xs uppercase tracking-widest"
                        >
                          Accept Match
                        </Button>
                      </div>
                    </div>
                  )}
                </CardContent>
              </Card>
            ))}
          </div>
        ) : (
          <div className="bg-white rounded-md border border-carry-light/10 p-20 flex flex-col items-center text-center space-y-4">
            <div className="w-16 h-16 rounded-full bg-carry-bg flex items-center justify-center text-carry-muted">
              <Search className="w-8 h-8" />
            </div>
            <h3 className="text-xl font-bold text-carry-darker">No matches found yet</h3>
            <p className="text-gray-500 max-w-sm">Our matching engine is constantly looking for compatible pairings. Check back soon or try expanding your search criteria.</p>
            <Button variant="outline" className="font-bold h-12 px-8">Refresh Engine</Button>
          </div>
        )}
      </div>
    </AccountLayout>
  );
}
